In [80]:
import numpy as np

In [81]:
lst = [1, 2, 3, 4, 5]
lst

[1, 2, 3, 4, 5]

In [82]:
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [83]:
type(arr)

numpy.ndarray

In [84]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [85]:
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
matrix[0]

array([1, 2, 3])

In [87]:
matrix[0,2]

3

In [88]:
matrix[0][2]

3

In [89]:
matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [90]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [91]:
vector = np.array([1, 2, 3, 4, 5])
print(vector)
vector.ndim

[1 2 3 4 5]


1

In [92]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [93]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [94]:
vector = np.array([1, 2, 3, 4, 5], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


10

In [95]:
expand  = np.expand_dims(np.array([1, 2, 3, 4, 5]), axis = 0)
print(expand)
expand.ndim

[[1 2 3 4 5]]


2

In [96]:
print(vector, vector.ndim)
vector = np.squeeze(vector)
print(vector, vector.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]] 10
[1 2 3 4 5] 1


In [97]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [99]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [100]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [101]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
np.random.rand()

0.3855172091152336

In [103]:
np.random.rand(5)

array([0.70389353, 0.16694748, 0.24017947, 0.43035217, 0.32822813])

In [104]:
np.random.rand(5,5)

array([[0.73400217, 0.75181015, 0.31062086, 0.32511884, 0.28170624],
       [0.61528501, 0.29503332, 0.10983012, 0.51978814, 0.23910027],
       [0.54757084, 0.66912823, 0.67750247, 0.70175249, 0.6133402 ],
       [0.30784859, 0.01736578, 0.72370009, 0.47966244, 0.27197889],
       [0.26658751, 0.35441702, 0.0899117 , 0.76189718, 0.4910057 ]])

In [105]:
rand_arr = np.random.randint(0,100,(6,5))

In [106]:
rand_arr.shape

(6, 5)

In [107]:
rand_arr

array([[ 2, 30,  5, 98,  5],
       [18, 76, 14, 12, 26],
       [72, 47, 86, 15, 38],
       [51, 20, 41, 83, 94],
       [58, 32, 47, 11, 31],
       [67, 47, 15, 26, 74]])

In [108]:
rand_arr.reshape(15,2)

array([[ 2, 30],
       [ 5, 98],
       [ 5, 18],
       [76, 14],
       [12, 26],
       [72, 47],
       [86, 15],
       [38, 51],
       [20, 41],
       [83, 94],
       [58, 32],
       [47, 11],
       [31, 67],
       [47, 15],
       [26, 74]])

In [109]:
rand_arr.max(1)

array([98, 76, 86, 94, 58, 74])

In [110]:
rand_arr.min(0)

array([ 2, 20,  5, 11,  5])

In [111]:
rand_arr.argmax()

3

In [112]:
rand_arr.ptp()

96

In [115]:
rand_arr.mean()

41.36666666666667

In [116]:
np.median(rand_arr)

35.0

In [117]:
rand_arr.std()

28.258902235500152

In [118]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [119]:
np.concatenate([a, b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])