In [71]:
import numpy as np

In [72]:
A =  np.array([[1,3],[4,6]])
A_inv=np.linalg.inv(A)
print(A)
print(A_inv)


[[1 3]
 [4 6]]
[[-1.          0.5       ]
 [ 0.66666667 -0.16666667]]


In [73]:
AxA_inv=np.dot(A,A_inv)
#print AxA_inv round to 0 decimal places
print(np.around(AxA_inv,decimals=0))

[[ 1.  0.]
 [-0.  1.]]


In [74]:
values, vectors =np.linalg.eig(A)
print(values)
print(vectors)

[-0.77200187  7.77200187]
[[-0.8610177  -0.40503571]
 [ 0.50857499 -0.91430087]]


In [75]:
vectors.T[0]

array([-0.8610177 ,  0.50857499])

In [76]:
vectors.T[1]

array([-0.40503571, -0.91430087])

In [77]:
vectors.T[0][0]/vectors.T[0][1]

-1.6930004681646913

In [78]:
v2=[[0,0]]
v2[0][0]=vectors.T[0][0]/vectors.T[0][1]
v2[0][1]=vectors.T[0][1]/vectors.T[0][1]
print(v2)

[[-1.6930004681646913, 1.0]]


In [79]:
(vectors.T[0][1]**2+vectors.T[0][0]**2)**(1/2)

1.0

In [80]:
np.matmul(A,vectors.T[0])

array([ 0.66470728, -0.39262085])

In [81]:
values[0]*vectors.T[0]

array([ 0.66470728, -0.39262085])

In [82]:
np.matmul(A,vectors.T[1])

array([-3.14793831, -7.10594804])

In [83]:
values[1]*vectors.T[1]

array([-3.14793831, -7.10594804])